use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(Tblfee::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Tblfee::Id)
                            .big_integer()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Tblfee::CreatedAt).timestamp_with_time_zone())
                    .col(ColumnDef::new(Tblfee::UpdatedAt).timestamp_with_time_zone())
                    .col(
                        ColumnDef::new(Tblfee::AdmSession)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Tblfee::AdmYear)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(ColumnDef::new(Tblfee::Dod).date())
                    .col(ColumnDef::new(Tblfee::Submit).text().not_null().default(""))
                    .col(ColumnDef::new(Tblfee::Prog).text().not_null().default(""))
                    .col(ColumnDef::new(Tblfee::Enroll).text().not_null().default(""))
                    .col(
                        ColumnDef::new(Tblfee::Student)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Tblfee::YearSem)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Tblfee::Category)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(ColumnDef::new(Tblfee::Dob).text().not_null().default(""))
                    .col(
                        ColumnDef::new(Tblfee::Contact)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Tblfee::Deposit)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(ColumnDef::new(Tblfee::Nsd).text().not_null().default(""))
                    .col(ColumnDef::new(Tblfee::Fee).text().not_null().default(""))
                    .col(
                        ColumnDef::new(Tblfee::Courses)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Tblfee::Remarks)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Tblfee::DepositBy)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(ColumnDef::new(Tblfee::Ts).text().not_null().default(""))
                    .col(ColumnDef::new(Tblfee::Medium).text().not_null().default(""))
                    .col(
                        ColumnDef::new(Tblfee::MotherName)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Tblfee::FatherName)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Tblfee::Username)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Tblfee::ControlId)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Tblfee::Descrepency)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Tblfee::University)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Tblfee::PaymentMode)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Tblfee::TransId)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(ColumnDef::new(Tblfee::Bank).text().not_null().default(""))
                    .col(ColumnDef::new(Tblfee::Rm).text().not_null().default(""))
                    .col(
                        ColumnDef::new(Tblfee::IsReconciled)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Tblfee::OnlineExported)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_tblfee_enroll")
                    .table(Tblfee::Table)
                    .col(Tblfee::Enroll)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_tblfee_contact")
                    .table(Tblfee::Table)
                    .col(Tblfee::Contact)
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(Tblfee::Table).to_owned())
            .await
    }
}

#[derive(Iden)]
enum Tblfee {
    Table,
    Id,
    CreatedAt,
    UpdatedAt,
    AdmSession,
    AdmYear,
    Dod,
    Submit,
    Prog,
    Enroll,
    Student,
    YearSem,
    Category,
    Dob,
    Contact,
    Deposit,
    Nsd,
    Fee,
    Courses,
    Remarks,
    DepositBy,
    Ts,
    Medium,
    MotherName,
    FatherName,
    Username,
    ControlId,
    Descrepency,
    University,
    PaymentMode,
    TransId,
    Bank,
    Rm,
    IsReconciled,
    OnlineExported,
}
