[package]
name = "nirmancampus-website"
version.workspace = true
edition.workspace = true

[dependencies]
lariv-rs = { workspace = true }
nirmancampus-common = { workspace = true }
nirmancampus-announcements = { workspace = true }
nirmancampus-programs = { workspace = true }
frunk = { workspace = true }
frunk_core = { workspace = true }
sea-orm = { workspace = true }
sea-orm-migration = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true, features = ["multipart"] }
serde = { workspace = true }
maud = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
calamine = "0.26"
hmac = "0.12"
sha2 = "0.10"
