[package]
name = "nirmancampus-studentfees"
version.workspace = true
edition.workspace = true

[dependencies]
lariv-rs = { workspace = true }
nirmancampus-common = { workspace = true }
frunk = { workspace = true }
frunk_core = { workspace = true }
sea-orm = { workspace = true, features = ["sqlx-mysql"] }
sea-orm-migration = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true, features = ["multipart"] }
calamine = "0.26"
serde = { workspace = true }
maud = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
